site_name: DisBot
repo_name: griceturrble/disbot
repo_url: https://github.com/griceturrble/disbot
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.annotate
    - toc.integrate

plugins:
  - search

nav:
  - index.md
  - getting_started.md
  - explore.md

markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
