site_name: DisBot
theme:
  name: material
  features:
    - content.code.annotate
    - toc.integrate

nav:
  - index.md
  - explore.md

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
